[package]
name = "colonize_common"
version = "0.1.0"
edition = "2018"
authors = ["Nikita Pekin <nikita@frecency.com>"]
publish = false

[dependencies]
building-blocks = { version = "0.4.3", default-features = false, features = ["mesh", "snappy"] }